### ISSUE TITLE
Inquiry about Code Completeness and Project Structure

### ISSUE THREAD

**Issue by TronYY** [sdycodes/Learning-to-Assign-with-Fairness#1]
Useful work! But I am not entirely certain if all the necessary components of the program are included in the repository. Could you provide a brief overview of the project's code structure?

For example, from my understanding, the KM.py file appears to be a potential candidate for the main program in the LAF directory. However, when I try to execute it, I encounter an issue where four parameters seem to be missing in the main function call.

Look forward to your response. Thanks.

**Comment by dingyuan-shi** [comment]
Every methods is self contained in its directory. However, the algorithms should be called by a simulator, which is developed by ride hailing platforms such as Didi Chuxing and Uber. We are not authorized to open source their simulator due to some commercial constraints and data security issue. 
If you want to execute the algorithms, you can develop your own simulator.

**Comment by TronYY** [comment]
I would like to ask if you have any recommendations for open-source vehicle dispatch simulators. Most of the simulators I found in github are related to Didi and are not open-source.
